title: Fluxtion DataFlow
description: Documentation for Fluxtion DataFlow
theme: just-the-docs

url: https://telaminai.github.io/dataflow-docs/

aux_links:
  DataFlow repo: https://telaminai.github.io/dataflow-docs/

color_scheme: fluxtion_style

compress_html:
  ignore:
    envs: all

kramdown:
  syntax_highlighter_opts:
    block:
      line_numbers: true

# Build settings
plugins:
  - jekyll-feed

callouts:
  info:
    color: blue
  note:
    title: NOTE
    color: blue
  warning:
    title: WARNING
    color: red