title: Fluxtion DataFlow
description: Documentation for Fluxtion DataFlow
theme: just-the-docs

url: https://telaminai.github.io/dataflow-docs/

aux_links:
  DataFlow repo: https://telaminai.github.io/dataflow-docs/

color_scheme: fluxtion_style

compress_html:
  ignore:
    envs: all

kramdown:
  syntax_highlighter_opts:
    block:
      line_numbers: true

# Build settings
plugins:
  - jekyll-feed

callouts:
  info:
    color: blue
  note:
    title: NOTE
    color: blue
  warning:
    title: WARNING
    color: red


#source directories
dataflow_version: 1.0.0

mermaid:
  # Version of mermaid library
  # Pick an available version from https://cdn.jsdelivr.net/npm/mermaid/
  version: "9.1.3"

#mermaid style
mermaid_eventProcessor: style EventProcessor fill:#e9ebe4,stroke:#333,stroke-width:1px
mermaid_eventHandler: classDef eventHandler color:#022e1f,fill:#aaa3ff,stroke:#000;
mermaid_graphNode: classDef graphNode color:#022e1f,fill:#00cfff,stroke:#000;
mermaid_exportedService: classDef exportedService color:#022e1f,fill:#aaa3ff,stroke:#000;
mermaid_white: classDef color:#022e1f,fill:#fff;
mermaid_black: classDef black color:#fff,fill:#000;